name: Android CI

on:
  push:
    branches: [ "master" ]
    tags: ["*"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Gradle Build Action
      uses: gradle/gradle-build-action@v3.5.0
      with:
        # Gradle command line arguments (supports multi-line input)
        arguments: assembleRelease
